credentials:
  usernames:
    admin:
      name: Admin User
      email: admin@gmail.com
      password: "123"
      status: "active"
cookie:
  expiry_days: 30
  key: "random_signature_key_warp_speed"
  name: "warp_speed_auth_cookie"
preauthorized:
  emails:
  - admin@gmail.com
